feature/extract period info
statisticsnorway/datadoc pull request #135
Opened 2024-01-26 07:37 UTC by mmwinther

- Extract time period from dapla dataset path - set up class, method and test for extracting date from
- Started some work
- First implementation of contains_data_from
- Just committing what is done today - code not working
- Temp save - code not working
- Formatting
- Temp save - code not working
- Improve structure for test data
- Dataclass to store date format information
- Remove non-implemented test cases
- Raise exception in categorize method

2024-01-29 12:46 UTC, jonolehagemo approved these changes

2024-01-29 12:51 UTC, jonolehagemo requested changes
The checks for correct periods in wrong order is missing

2024-01-29 13:30 UTC, mmwinther commented
> The checks for correct periods in wrong order is missing

@jonolehagemo I think we agredd to take this as part of DPMETA-20

2024-01-30 07:26 UTC, jonolehagemo approved these changes

2024-01-30 09:04 UTC, tilen1976 approved these changes
Looks good!

2024-01-30 09:47 UTC, merged